version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - nest_server_volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  nest_server_volume:
    external: true
